title: Your Full Name
description: Ph.D. Applicant in Computer Science

position: Ph.D. Applicant in Computer Science
university: Your University
location: City, Country

email: your-email@example.com
github_username: your-github-name
linkedin: https://www.linkedin.com/in/your-link
google_scholar: https://scholar.google.com/your-link

avatar: /assets/images/profile.jpg
cv: /assets/files/CV.pdf

lang: en-US

plugins:
  - jekyll-seo-tag