title: Liying Liu
description: Liying Liu's Profile

nameZh: 刘丽颖
position: Second-year M.S. student at BJUT
university: Beijing University of Technology
location: Beijing, China

email: lying.liu@outlook.com
github_username: Liu-Liying
linkedin: www.linkedin.com/in/liying-liu-1a970b41b

avatar: /assets/images/profile.jpg
cv: /assets/files/CV.pdf

lang: en-US

plugins:
  - jekyll-seo-tag